language: cpp
dist: trusty
sudo: required
compiler:
  - gcc
os:
  - linux
before_install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - sudo dpkg -i devkitpro-pacman.deb
  - sudo dkp-pacman -S 3ds-dev 3ds-zlib 3ds-tinyxml2 3ds-mpg123 3ds-libpng 3ds-mbedtls 3ds-curl --noconfirm
script:
  - make -C m3dialib/
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipents:
      - stunthacks@gmail.com
    on_success: never
    on_failure: always
env:
  global:
    - DEVKITPRO="/opt/devkitpro"
    - DEVKITARM="/opt/devkitpro/devkitARM"
